- name: CSE356 HW1
  hosts: hw1
  become: True
  tasks:
    - name: Install nginx command
      apt:
        name: nginx
        state: latest

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: Get installed version
      command: nginx -v

    - name: Status of nginx service
      command: systemctl status nginx

    - name: Clone CSE356 Repository
      command: git clone https://github.com/aisenkim/CSE356.git

    - name: Move hw0 files from cloned respository to root directory
      command: mv CSE356/hw0/hw0.html CSE356/hw0/lolli.jpg /var/www/html

    - name: Edit nginx configuration to use hw0.html file in root dir
      ansible.builtin.replace:
        path: /etc/nginx/sites-available/default
        regexp: '\bindex.nginx-debian.html\b'
        replace: "hw0.html"

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
